package com.timetable.ui.generate;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class ExportUIController {
	@FXML
	private Button exportButton;

	// Event Listener on Button[#exportButton].onAction
	@FXML
	public void exportTimetable(ActionEvent event) {
		// TODO Autogenerated
	}
}
